### ISSUE TITLE
Final Jpeg Orthomap

### ISSUE THREAD

**Issue by ShadiZaki** [UASLab/ImageAnalysis#13]
Is there a way to write the final output directly in jpg format? Thanks :)

**Comment by clolsonus** [comment]
There is no direct way to do that right now.  I will sometimes take a screenshot of the visualizer window zoomed out to show the whole data set.  I know that's not what you are asking about.  At some point I would like to create a geotiff output option, but that requires making choices about which image fragments to value over others and the main point of this project (differentiating from other projects like ODM) is that all the original images are preserved and viewable in place/in context in the visualizer tool.  Hope that helps clarify.

Best regards,

Curt.
