### ISSUE TITLE
No module named 'props'

### ISSUE THREAD

**Issue by hanxiaoyuyu** [UASLab/ImageAnalysis#4]
when i run the script ,not find module named 'props'
 from props import getNode
ModuleNotFoundError: No module named 'props'

**Comment by clolsonus** [comment]
For others that might bump into this same error message.  The required dependency to install is found here:

    https://github.com/AuraUAS/aura-props

You only need to do step #1 of the installation instructions (just the python part) to support the Image Analysis tools.  Doing part 2 of the aura-props install doesn't hurt anything, but isn't needed.
