### ISSUE TITLE
shebang calls system python

### ISSUE THREAD

**Issue by p-vitt** [UASLab/ImageAnalysis#8]
The shebang in e.g. scripts/process.py points to the system version of python. However, if you installed another python in some other directory (like it is common to do on Macs with MacPorts), the script fails because it won't find the installed modules. Instead of `#!/usr/bin/python3` it should be `#!/usr/bin/env python3`, which calls the correct python for a given environment.

**Comment by clolsonus** [comment]
This is a fair suggestion.  I have pushed the requested change.
